# Generated by Django 4.0.1 on 2022-09-10 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_wallettrxinformation_transaction_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettrxinformation',
            options={'verbose_name_plural': 'Wallet Transaction Information'},
        ),
        migrations.AddField(
            model_name='wallettrxinformation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
