# Generated by Django 4.0.1 on 2022-09-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_wallettrxinformation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettrxinformation',
            options={'ordering': ('-date',), 'verbose_name_plural': 'Wallet Transaction Information'},
        ),
    ]
