# Generated by Django 4.0.1 on 2022-11-23 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_wallettrxinformation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trx_ref', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('amount', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('payment_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
