# Generated by Django 4.0.1 on 2022-11-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_incomingpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingpayment',
            name='message',
            field=models.TextField(default='Successful', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomingpayment',
            name='status',
            field=models.CharField(default='success', max_length=20),
            preserve_default=False,
        ),
    ]
