# Generated by Django 4.0.1 on 2022-09-26 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6, null=True)),
                ('token_type', models.CharField(choices=[('ACCOUNT_VERIFICATION', 'ACCOUNT_VERIFICATION'), ('PASSWORD_RESET', 'PASSWORD_RESET'), ('AUTH_TOKEN', 'AUTH_TOKEN')], default='PASSWORD_RESET', max_length=100)),
                ('has_been_confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
