# Generated by Django 4.0.1 on 2022-11-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_vendorinformation_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinformation',
            name='sub_account_code',
            field=models.CharField(default='hello', max_length=10),
            preserve_default=False,
        ),
    ]
