# Generated by Django 4.0.1 on 2022-11-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_vendorinformation_sub_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinformation',
            name='sub_account_code',
            field=models.CharField(max_length=50),
        ),
    ]
