# Generated by Django 4.0.1 on 2022-11-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_category_alter_vendorinformation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorinformation',
            name='category',
        ),
        migrations.AddField(
            model_name='vendorinformation',
            name='category',
            field=models.ManyToManyField(default=None, to='business.Category'),
        ),
    ]
