# Generated by Django 4.0.1 on 2022-11-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_remove_vendorinformation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinformation',
            name='category',
            field=models.ManyToManyField(to='business.Category'),
        ),
    ]
