# Generated by Django 4.0.1 on 2022-11-22 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_vendorinformation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinformation',
            name='closing_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 22, 14, 52, 37, 47505, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorinformation',
            name='opening_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 22, 14, 52, 45, 829827, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
