# Generated by Django 4.0.1 on 2022-11-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_vendorinformation_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinformation',
            name='delivery_time',
            field=models.CharField(default='10 - 15', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorinformation',
            name='successful_order_count',
            field=models.IntegerField(default=0),
        ),
    ]
