# Generated by Django 4.0.1 on 2022-11-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_vendorinformation_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorinformation',
            options={'ordering': ('-successful_order_count', 'name'), 'verbose_name_plural': 'VendorInformation'},
        ),
    ]
