# Generated by Django 4.0.1 on 2022-09-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
