# Generated by Django 4.0.1 on 2022-09-05 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderinformation_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
