# Generated by Django 4.0.1 on 2022-09-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderinformation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinformation',
            name='order_detail',
            field=models.TextField(max_length=5000),
        ),
    ]
