# Generated by Django 4.0.1 on 2022-09-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderinformation_order_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='payment_method',
            field=models.CharField(default='H', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderinformation',
            name='trx_ref',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
