# Generated by Django 4.0.1 on 2022-11-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderinformation_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='message',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
