# Generated by Django 4.0.1 on 2022-11-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderinformation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='order_id',
            field=models.CharField(default='hello', max_length=10),
            preserve_default=False,
        ),
    ]
