# Generated by Django 4.0.1 on 2022-11-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderinformation_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinformation',
            name='trx_ref',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
