# Generated by Django 4.0.1 on 2022-11-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderinformation_trx_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinformation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
